### PR TITLE
Add an interpreter REPL mode

### PR DESCRIPTION
**Pull request by timholy**
This adds a new mode that's rather fun. Try entering a command at the REPL and then hit Meta-i (on the same line, don't hit Enter). Then, for an intro to what can be done type `?`.

This requires https://github.com/timholy/Revise.jl/pull/243, fully up-to-date JuliaInterpreter, and incorporates #60.

### CODE REVIEW

**Comment by KristofferC** [comment]
```
interpret> 1+1
┌ Error: Error in the keymap
│   exception =
│    UndefVarError: clear_nlines not defined
│    Stacktrace:
│     [1] getproperty at .\sysimg.jl:13 [inlined]
│     [2] interpret(::REPL.LineEdit.MIState) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:336
│     [3] (::getfield(Rebugger, Symbol("##24#27")))(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any,N} where N) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:484
│     [4] #invokelatest#1 at .\essentials.jl:742 [inlined]
│     [5] invokelatest at .\essentials.jl:741 [inlined]
```

**Comment by timholy** [comment]
Doh! https://github.com/timholy/HeaderREPLs.jl/pull/9

**Comment by KristofferC** [comment]
Just pressing `alt + i` gives

```
interpret> ┌ Error: Error in the keymap
│   exception =
│    expression is not a function call or symbol
│    Stacktrace:
│     [1] error(::String) at .\error.jl:33
│     [2] extract_args(::Module, ::Nothing) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\JuliaInterpreter.jl:1032
│     [3] interpret(::REPL.LineEdit.MIState) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:199
│     [4] (::getfield(Rebugger, Symbol("##24#27")))(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any,N} where N) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:484
│     [5] #invokelatest#1 at .\essentials.jl:742 [inlined]
│     [6] invokelatest at .\essentials.jl:741 [inlined]
```

**Comment by timholy** [comment]
Not anymore :smile:

**Comment by KristofferC** [comment]
Entering `rand(5)` and pressing the right arrow key:

```
interpret> rand(5)[ Info: tracking Random

rand(dims::Integer...) in Random at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Random\src\Random.jl:243
  dims = (5,)
ERROR: AssertionError: issorted(linenos)
Stacktrace:
 [1] expression_lines(::Method) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\printing.jl:52
 [2] reset_frame!(::Rebugger.InterpretHeader, ::Bool) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:360 [3] interpret(::REPL.LineEdit.MIState) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:288
 [4] (::getfield(Rebugger, Symbol("##24#27")))(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any,N} where N) at C:\Users\Kristoffer\.julia\packages\Rebugger\6cJMB\src\ui.jl:484
```

**Comment by timholy** [comment]
Thanks! Should be better now?

**Comment by timholy** [comment]
Should be better now. Thanks for trying it!

**Comment by KristofferC** [comment]
🎉

**Pull request merged**
