### PR TITLE
Change the default keybindings

### PR DESCRIPTION
**Pull request by timholy**
This switches to Alt-e and Alt-s for all users. It also enhances the deprecation mechanism so we can deprecate keys for each action.

Finally, a couple of other miscellaneous improvements are included. This will be tagged and the version used for discourse announcement.

### CODE REVIEW

**Comment by stillyslalom** [comment]
Alt-e and Alt-s give `´` and `ß`, respectively, on OSX. Is there a set of bindings that we can expect to work on all major platforms?

**Comment by timholy** [comment]
Drat!!! I thought we had this figured out.

The short answer is no, we haven't figured out a set of bindings that should work everywhere. Do you want to try picking a couple for OSX and let us know what seems convenient? We can make it OSX-specific. Note there's documentation on how to customize it: https://timholy.github.io/Rebugger.jl/latest/config.html#Customize-keybindings-1

**Comment by timholy** [comment]
Let's move this to #28.

**Comment by timholy** [comment]
@stillyslalom can you clarify whether the resolution in #28 works for you?

**Pull request merged**
